version: "2"
services:
   namenode:
      image: apache/hadoop:3
      hostname: namenode
      entrypoint: ["sh", "-c"]
      command: 
        - "sudo adduser -D ${HDFS_DATANODE_USER} &&
          chown -R ${HDFS_NAMENODE_USER}:${HDFS_NAMENODE_USER} ${ENSURE_NAMENODE_DIR} &&
          su - ${HDFS_DATANODE_USER} -c 'hdfs datanode' &&
          ${HADOOP_HOME}/sbin/start-dfs.sh"
      ports:
        - 9870:9870
      env_file:
        - ./config
   datanode:
      image: apache/hadoop:3
      entrypoint: ["sh", "-c"]
      command: "sudo adduser -D ${HDFS_DATANODE_USER} && su - ${HDFS_DATANODE_USER} -c 'hdfs datanode'"
      env_file:
        - ./config
   resourcemanager:
      image: apache/hadoop:3
      hostname: resourcemanager
      entrypoint: ["sh", "-c"]
      command:
        - "sudo adduser -D ${YARN_RESOURCEMANAGER_USER} && su - ${YARN_RESOURCEMANAGER_USER} -c 'yarn resourcemanager'"
      ports:
        - 8088:8088
      env_file:
        - ./config
      volumes:
        - ./test.sh:/opt/test.sh
   nodemanager:
      image: apache/hadoop:3
      entrypoint: ["sh", "-c"]
      command:
        - "sudo adduser -D ${YARN_NODEMANAGER_USER} && su - ${YARN_NODEMANAGER_USER} -c 'yarn nodemanager'"
      env_file:
        - ./config