version: "2"
services:
   namenode:
      image: apache/hadoop:3
      hostname: namenode
      entrypoint: [
        "su", "${HDFS_NAMENODE_USER}",
        "&&", "hdfs", "namenode"
      ]
      command:
        - chown -R ${HDFS_NAMENODE_USER}:${HDFS_NAMENODE_USER} ${ENSURE_NAMENODE_DIR}
        - ${HADOOP_HOME}/sbin/start-dfs.sh
      ports:
        - 9870:9870
      env_file:
        - ./config
   datanode:
      image: apache/hadoop:3
      entrypoint: [
        "su", "${HDFS_DATANODE_USER}",
        "&&", "hdfs", "datanode"
      ]
      env_file:
        - ./config
   resourcemanager:
      image: apache/hadoop:3
      hostname: resourcemanager
      entrypoint: [
        "su", "${YARN_RESOURCEMANAGER_USER}",
        "&&", "yarn", "resourcemanager"
      ]
      ports:
        - 8088:8088
      env_file:
        - ./config
      volumes:
        - ./test.sh:/opt/test.sh
   nodemanager:
      image: apache/hadoop:3
      entrypoint: [
        "su", "${YARN_NODEMANAGER_USER}",
        "&&", "yarn", "nodemanager"
      ]
      env_file:
        - ./config