version: "2"
services:
  namenode:
    # image: apache/hadoop:3
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: namenode
    entrypoint: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  datanode1:
    # image: apache/hadoop:3
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ["hdfs", "datanode"]
    ports:
      - 50075:50075
    env_file:
      - ./config
  datanode2:
    # image: apache/hadoop:3
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ["hdfs", "datanode"]
    ports:
      - 50076:50075
    env_file:
      - ./config      
  resourcemanager:
    # image: apache/hadoop:3
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: resourcemanager
    entrypoint: ["yarn", "resourcemanager"]
    ports:
      - 8030:8030
      - 8031:8031
      - 8032:8032
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
  nodemanager:
    # image: apache/hadoop:3
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ["yarn", "nodemanager"]
    ports:
      - 8042:8042
    env_file:
      - ./config