version: "2"
services:
  namenode:
    image: apache/hadoop:3
    user: hdfs
    hostname: namenode
    entrypoint: ["sh", "-c", "adduser --disabled-password --gecos '' hdfs; hdfs namenode"]
    ports:
      - 9870:9870
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  datanode:
    image: apache/hadoop:3
    user: hdfs
    entrypoint: ["sh", "-c", "adduser --disabled-password --gecos '' hdfs; hdfs datanode"]
    env_file:
      - ./config      
  resourcemanager:
    image: apache/hadoop:3
    user: yarn
    hostname: resourcemanager
    entrypoint: ["sh", "-c", "adduser --disabled-password --gecos '' yarn; yarn resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
  nodemanager:
    image: apache/hadoop:3
    user: yarn
    entrypoint: ["sh", "-c", "adduser --disabled-password --gecos '' yarn; yarn nodemanager"]
    env_file:
      - ./config